#############################
# ARM 1 
#############################
arm_1_joint_1:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_1_joint_2:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]

    
arm_1_joint_3:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]
  

arm_1_joint_4:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_1_joint_5:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_1_joint_6:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]

#############################
# ARM 2 
#############################
arm_2_joint_1:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_2_joint_2:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]

    
arm_2_joint_3:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]
  

arm_2_joint_4:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_2_joint_5:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]]


arm_2_joint_6:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]



#############################
# ARM 3 
#############################
arm_3_joint_1:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_3_joint_2:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]

    
arm_3_joint_3:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]
  

arm_3_joint_4:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_3_joint_5:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]


arm_3_joint_6:
  brake_present: true
  control_mode: 0xD4
  gains: [1000.0,10.0,1.0,0.7,0.007]



