trajectory:
  type: sine #sine, step, smoother
  frequency: 1
  repeat: 2
  
motor:
  config_path: ${PWD}/motor/hqr3_pos3b.yaml
  id: [41,11,12,13,14,15,16,17,21,22,23,24,25,26,27]
  set_point:  {position: 1.0, velocity: 2.0, torque: 10.0, current: 2} #rad,rad/s,Nm,A
  homing:     [0,-0.5,-0.7,0.5, -1.2,-0.5,0.5,0.5,0.5,0.7,-0.5,1.2,0.5,-0.5,-0.5]
  trajectory: [0,-0.5,-0.7,0.5, -1.2,-0.5,0.5,0.5,0.5,0.7,-0.5,1.2,0.5,-0.5,-0.5]
  


    

