trajectory:
  type: sine #spline, smoother, step, sine, stair, chirp
  frequency: 0.5
  repeat: 50
  
motor:
  config_path: ${PWD}/motor/repair_pos3b.yaml
  id: [1,41,11,12,13,14,15,16,17,21,22,23,24,25,26,27]
  # id: [11,12,13,14,15,16,17]
  set_point:  {position: 1.0, velocity: 2.0, torque: 10.0, current: 2} #rad,rad/s,Nm,A
  homing:     [100,
               0,
              -0.5, -0.7, 0.5, -1.2, -0.5, 0.5, 0.5, 
               0.5, 0.7, -0.5, 1.2, 0.5, -0.5, -0.5]
  #homing:     [-0.5,-0.7,0.5, -1.2,-0.5,0.5,0.5]
  trajectory: [102,
               0.5, 
              -1, -1.2, 1, -1.7, -1, 1, 1,
               1, 1.2, -1, 1.7, 1, -1, -1]
  
  # trajectory: [102,
  #              0.2, 
  #             -0.75, -0.95, 0.75, -1.45, -0.75, 0.75, 0.75,
  #              0.75, 0.95, -0.75, 1.45, 0.75, -0.75, -0.75]
  #trajectory: [-0.75,-0.95,0.75, -1.45,-0.75,0.75,0.75]


    

