#############################
# LEG 1 
#############################
leg_1_joint_3:
  control_mode: 0xDD
  gains: [0,0,0,0,0]

#############################
# LEG 2
#############################
leg_2_joint_3:
  control_mode: 0xDD
  gains: [0,0,0,0,0]

#############################
# LEG 3
#############################
leg_3_joint_3:
  control_mode: 0xDD
  gains: [0,0,0,0,0]
#############################
# LEG 4
#############################
leg_4_joint_3:
  control_mode: 0xDD
  gains: [0,0,0,0,0]
