trajectory:
  type: polynomial #step, sine, cosine, chirp
  frequency: 1
  repeat: 2
  
motor:
  config_path: ${PWD}/motor/mirror_pos3b.yaml
  id: [21,22,23,24,25,26,11,12,13,14,15,16,31,32,33,34,35,36]
  set_point:  {position: 1.0, velocity: 2.0, torque: 10.0, current: 2} #rad,rad/s,Nm,A
  homing:     [-0.75, -1.0, -1.0, -0.75, 1.0, -0.75,
               -0.75, -1.0, -1.0, -0.75, 1.0, -0.75,
               -0.75, -1.0, -1.0, -0.75, 1.0, -0.75]
  trajectory: [0.0, -1.9, -2.3, 0.0, -0.4, 0.0,
               0.0, -1.9, -2.3, 0.0, -0.4, 0.0,
               0.0, -1.9, -2.3, 0.0, -0.4, 0.0]
simulation:
  imu_id: [102,103]
  ft_id: [110,111]
  pow_id: [201]

