network:
  #protocol: zipc
  #hostname: /tmp/ecat_master
  
  protocol: iddp #tcp #iddp #udp
  hostname: localhost #10.240.23.30 #localhost #192.168.99.10 #192.168.9.99 #10.240.22.49
  port: 5000 #54321(UDP)
  timeout: 1000

general:
  period_ms: 1
  logging: true

robot:
  robot_id_map_path: &robot_id_map_path '${PWD}/robot_id_map/repair/repair_id_map.yaml' 
  robot_control_path: ${PWD}/robot_control/repair/repair_control.yaml

