network:
  hostname: 192.168.99.10 #10.240.23.30 #localhost #192.168.99.10 #192.168.9.99 #10.240.22.49
  port: 54321
  timeout: 1000

################position################
#control_mode: position
#position gains
#gains: [200.0,0.0,10.0,0.0,0.0]
################position################

################impedance################
control_mode: impedance
#impedance gains
# stiffness, damping, tau_p, tau_f, tau_d
gains: [1000.0,10.0,1.0,0.7,0.007]
################impedance################


UDP_period_ms: 4
homing_position: {11: -0.75, 12: -1.0, 13: -1.0, 14: -0.75, 15: 1.0, 16: -0.75,
                  21: -0.75, 22: -1.0, 23: -1.0, 24: -0.75, 25: 1.0, 26: -0.75,
                  31: -0.75, 32: -1.0, 33: -1.0, 34: -0.75, 35: 1.0, 36: -0.75}
homing_time_sec: 3
trajectory: {11: 0.0, 12: -1.9, 13: -2.3, 14: 0.0, 15: -0.4, 16: 0.0,
             21: 0.0, 22: -1.9, 23: -2.3, 24: 0.0, 25: -0.4, 26: 0.0,
             31: 0.0, 32: -1.9, 33: -2.3, 34: 0.0, 35: -0.4, 36: 0.0}
trajectory_time_sec: 3
repeat_trj: 3


slave_id_led: [16,26,35]

XBotInterface:
  urdf_path: ${PWD}/urdf/mirror.urdf
  srdf_path: ${PWD}/srdf/mirror.srdf
  joint_map_path: ${PWD}/joint_map/mirror_joint_map.yaml

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"

