#############################
# TORSO 
#############################
torso:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00

#############################
# ARM 1 
#############################
j_arm_1_1:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_1_2:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00

j_arm_1_3:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_1_4:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00

j_arm_1_5:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_1_6:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_1_7:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00

#############################
# ARM 2 
#############################
j_arm_2_1:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_2_2:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
j_arm_2_3:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_2_4:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00

j_arm_2_5:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_2_6:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
  
j_arm_2_7:
  motor_type: ADVRF #allowed ADVRF, Synapticon default ADVRF
  brake_present: false
  control_mode: 0x00
