trajectory:
  type: sine #spline, smoother, step, sine, stair, chirp
  frequency: 1
  repeat: 2
  
motor:
  config_path: ${PWD}/motor/robot_pos3b.yaml
  id: [1,2,3,4,5,6,7,8]
  set_point:  {position: 1.0, velocity: 2.0, torque: 10.0, current: 2} #rad,rad/s,Nm,A
  homing:     [-0.75,-1.0,-1.0,-0.75, 1.0,-0.75,-1.0,-1.0]
  trajectory: [ 0.00,-1.9,-2.3, 0.00,-0.4, 0.00,-1.9,-2.3]

valve:
  config_path: ${PWD}/valve/robot_forced4.yaml 
  id: [120,121,122,123]
  set_point:  {current: 2.5, position: 10.0, force: 10.0} #A,um micro-meter,N

pump:
  config_path: ${PWD}/pump/robot_pressured4.yaml
  id: [210]
  set_point:  {pressure: 128.0, velocity: 10.0, pwm: 30.0} #bar,RPM,Duty Cycle %
simulation:
  imu_id: [102]
  ft_id: [110,111]
  pow_id: [201]
