name: documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-copybutton
          sudo apt-get install doxygen
          sudo apt -y install graphviz
      - name: Sphinx and Doxygen build
        run: |
          make -C docs clean
          make -C docs html
          mkdir docs/build/html/library/ docs/build/html/gui docs/build/html/paper
          cd docs/library
          doxygen Doxyfile
          cd ../../
          cp -r docs/library/html/* docs/build/html/library/
          cd docs/gui
          doxygen Doxyfile
          cd ../../
          cp -r docs/gui/html/* docs/build/html/gui/
          cp -r docs/paper/* docs/build/html/paper/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
